<div class="block block-dashboard-info">
    <div class="block-title"><strong>Gift Card Information</strong></div>
    <div class="block-content">
        <div class="box box-information">
            <strong class="box-title">
                <span>Balance</span>
            </strong>
            <div class="box-content">
                <p>
                    <?php
                    /**
                     * @var \Mageplaza\GiftCard\Block\Customer\Info $block
                     */

                    echo $block->getBalance();
                    ?>
                </p>
            </div>
        </div>
        <?php if($block->getConfig() == '1'): ?>
        <div class="box box-newsletter">
            <strong class="box-title">
                <span>Redeem</span>
            </strong>
            <form class="form-inline" action="<?= $block->getUrl('giftcard/customer/redeem'); ?>" method="get">
                <input name="code" style="width: 300px" type="text" class="form-control" id="redeem" placeholder="Enter Gift Card Code">
                <button class="action subscribe primary"  type="submit" >Redeem</button>

            </form>
        </div>
        <?php endif ?>
    </div>
</div>
